using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.Services;

namespace ServicioW.ClienteWeb
{
    public partial class _default : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {

        }
        [WebMethod]
        public static string GetData(string PageNo)
        {
            System.Threading.Thread.Sleep(3000);
            //Insert it to our database
            string res =    "<h3>Page " + PageNo + "</h3><p>There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.</p>";
            return res;
          //  return "<h3>Page " + PageNo + "</h3><p>There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain.</p>";
            
        }
    }
}