//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ServiciosWeb.WepApi.bo.com.linkser.lnksrvssaup2 {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiciosEcommeLNKSoapBinding", Namespace="http://Servicio/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(me_set_Autho_Ecomm))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(me_get_Cons_Autho_Ecomm))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(me_set_Rever_Ecomm))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(me_get_Con_Autho_RangoFecha_Ecomm))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(setRegistrarResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(setRegistrar))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getRetoResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getReto))]
    public partial class ServiciosEcommeLNK : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getRetoOperationCompleted;
        
        private System.Threading.SendOrPostCallback setRegistrarOperationCompleted;
        
        private System.Threading.SendOrPostCallback me_get_Con_Autho_RangoFecha_EcommOperationCompleted;
        
        private System.Threading.SendOrPostCallback me_set_Rever_EcommOperationCompleted;
        
        private System.Threading.SendOrPostCallback me_get_Cons_Autho_EcommOperationCompleted;
        
        private System.Threading.SendOrPostCallback me_set_Autho_EcommOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiciosEcommeLNK() {
            this.Url = global::ServiciosWeb.WepApi.Properties.Settings.Default.ServiciosWeb_WepApi_bo_com_linkser_lnksrvssaup2_ServiciosEcommeLNK;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getRetoCompletedEventHandler getRetoCompleted;
        
        /// <remarks/>
        public event setRegistrarCompletedEventHandler setRegistrarCompleted;
        
        /// <remarks/>
        public event me_get_Con_Autho_RangoFecha_EcommCompletedEventHandler me_get_Con_Autho_RangoFecha_EcommCompleted;
        
        /// <remarks/>
        public event me_set_Rever_EcommCompletedEventHandler me_set_Rever_EcommCompleted;
        
        /// <remarks/>
        public event me_get_Cons_Autho_EcommCompletedEventHandler me_get_Cons_Autho_EcommCompleted;
        
        /// <remarks/>
        public event me_set_Autho_EcommCompletedEventHandler me_set_Autho_EcommCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicio/", ResponseNamespace="http://Servicio/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getReto() {
            object[] results = this.Invoke("getReto", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getRetoAsync() {
            this.getRetoAsync(null);
        }
        
        /// <remarks/>
        public void getRetoAsync(object userState) {
            if ((this.getRetoOperationCompleted == null)) {
                this.getRetoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRetoOperationCompleted);
            }
            this.InvokeAsync("getReto", new object[0], this.getRetoOperationCompleted, userState);
        }
        
        private void OngetRetoOperationCompleted(object arg) {
            if ((this.getRetoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRetoCompleted(this, new getRetoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicio/", ResponseNamespace="http://Servicio/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string setRegistrar([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string cod_institucion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string llave_publica, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string llave_registro) {
            object[] results = this.Invoke("setRegistrar", new object[] {
                        cod_institucion,
                        llave_publica,
                        llave_registro});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void setRegistrarAsync(string cod_institucion, string llave_publica, string llave_registro) {
            this.setRegistrarAsync(cod_institucion, llave_publica, llave_registro, null);
        }
        
        /// <remarks/>
        public void setRegistrarAsync(string cod_institucion, string llave_publica, string llave_registro, object userState) {
            if ((this.setRegistrarOperationCompleted == null)) {
                this.setRegistrarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetRegistrarOperationCompleted);
            }
            this.InvokeAsync("setRegistrar", new object[] {
                        cod_institucion,
                        llave_publica,
                        llave_registro}, this.setRegistrarOperationCompleted, userState);
        }
        
        private void OnsetRegistrarOperationCompleted(object arg) {
            if ((this.setRegistrarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setRegistrarCompleted(this, new setRegistrarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicio/", ResponseNamespace="http://Servicio/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] me_get_Con_Autho_RangoFecha_Ecomm([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string cod_institucion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string cod_comercio, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int fecha_inicio, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int fecha_fin, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string reto, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string validacionDigital, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string llave_registro) {
            object[] results = this.Invoke("me_get_Con_Autho_RangoFecha_Ecomm", new object[] {
                        cod_institucion,
                        cod_comercio,
                        fecha_inicio,
                        fecha_fin,
                        reto,
                        validacionDigital,
                        llave_registro});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void me_get_Con_Autho_RangoFecha_EcommAsync(string cod_institucion, string cod_comercio, int fecha_inicio, int fecha_fin, string reto, string validacionDigital, string llave_registro) {
            this.me_get_Con_Autho_RangoFecha_EcommAsync(cod_institucion, cod_comercio, fecha_inicio, fecha_fin, reto, validacionDigital, llave_registro, null);
        }
        
        /// <remarks/>
        public void me_get_Con_Autho_RangoFecha_EcommAsync(string cod_institucion, string cod_comercio, int fecha_inicio, int fecha_fin, string reto, string validacionDigital, string llave_registro, object userState) {
            if ((this.me_get_Con_Autho_RangoFecha_EcommOperationCompleted == null)) {
                this.me_get_Con_Autho_RangoFecha_EcommOperationCompleted = new System.Threading.SendOrPostCallback(this.Onme_get_Con_Autho_RangoFecha_EcommOperationCompleted);
            }
            this.InvokeAsync("me_get_Con_Autho_RangoFecha_Ecomm", new object[] {
                        cod_institucion,
                        cod_comercio,
                        fecha_inicio,
                        fecha_fin,
                        reto,
                        validacionDigital,
                        llave_registro}, this.me_get_Con_Autho_RangoFecha_EcommOperationCompleted, userState);
        }
        
        private void Onme_get_Con_Autho_RangoFecha_EcommOperationCompleted(object arg) {
            if ((this.me_get_Con_Autho_RangoFecha_EcommCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.me_get_Con_Autho_RangoFecha_EcommCompleted(this, new me_get_Con_Autho_RangoFecha_EcommCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicio/", ResponseNamespace="http://Servicio/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] me_set_Rever_Ecomm([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string cod_institucion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string secuencia, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int fecha_transaccion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int fecha_envio, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string hora_envio, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string reto, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string validacionDigital, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string llave_registro) {
            object[] results = this.Invoke("me_set_Rever_Ecomm", new object[] {
                        cod_institucion,
                        secuencia,
                        fecha_transaccion,
                        fecha_envio,
                        hora_envio,
                        reto,
                        validacionDigital,
                        llave_registro});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void me_set_Rever_EcommAsync(string cod_institucion, string secuencia, int fecha_transaccion, int fecha_envio, string hora_envio, string reto, string validacionDigital, string llave_registro) {
            this.me_set_Rever_EcommAsync(cod_institucion, secuencia, fecha_transaccion, fecha_envio, hora_envio, reto, validacionDigital, llave_registro, null);
        }
        
        /// <remarks/>
        public void me_set_Rever_EcommAsync(string cod_institucion, string secuencia, int fecha_transaccion, int fecha_envio, string hora_envio, string reto, string validacionDigital, string llave_registro, object userState) {
            if ((this.me_set_Rever_EcommOperationCompleted == null)) {
                this.me_set_Rever_EcommOperationCompleted = new System.Threading.SendOrPostCallback(this.Onme_set_Rever_EcommOperationCompleted);
            }
            this.InvokeAsync("me_set_Rever_Ecomm", new object[] {
                        cod_institucion,
                        secuencia,
                        fecha_transaccion,
                        fecha_envio,
                        hora_envio,
                        reto,
                        validacionDigital,
                        llave_registro}, this.me_set_Rever_EcommOperationCompleted, userState);
        }
        
        private void Onme_set_Rever_EcommOperationCompleted(object arg) {
            if ((this.me_set_Rever_EcommCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.me_set_Rever_EcommCompleted(this, new me_set_Rever_EcommCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicio/", ResponseNamespace="http://Servicio/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] me_get_Cons_Autho_Ecomm([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string cod_institucion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string secuencia, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string tarjeta, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string cod_comercio, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string cod_terminal, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int fecha_transaccion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string servicio, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string monto, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string moneda, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string fecha_expiracion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string reto, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string validacionDigital, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string llave_registro) {
            object[] results = this.Invoke("me_get_Cons_Autho_Ecomm", new object[] {
                        cod_institucion,
                        secuencia,
                        tarjeta,
                        cod_comercio,
                        cod_terminal,
                        fecha_transaccion,
                        servicio,
                        monto,
                        moneda,
                        fecha_expiracion,
                        reto,
                        validacionDigital,
                        llave_registro});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void me_get_Cons_Autho_EcommAsync(string cod_institucion, string secuencia, string tarjeta, string cod_comercio, string cod_terminal, int fecha_transaccion, string servicio, string monto, string moneda, string fecha_expiracion, string reto, string validacionDigital, string llave_registro) {
            this.me_get_Cons_Autho_EcommAsync(cod_institucion, secuencia, tarjeta, cod_comercio, cod_terminal, fecha_transaccion, servicio, monto, moneda, fecha_expiracion, reto, validacionDigital, llave_registro, null);
        }
        
        /// <remarks/>
        public void me_get_Cons_Autho_EcommAsync(string cod_institucion, string secuencia, string tarjeta, string cod_comercio, string cod_terminal, int fecha_transaccion, string servicio, string monto, string moneda, string fecha_expiracion, string reto, string validacionDigital, string llave_registro, object userState) {
            if ((this.me_get_Cons_Autho_EcommOperationCompleted == null)) {
                this.me_get_Cons_Autho_EcommOperationCompleted = new System.Threading.SendOrPostCallback(this.Onme_get_Cons_Autho_EcommOperationCompleted);
            }
            this.InvokeAsync("me_get_Cons_Autho_Ecomm", new object[] {
                        cod_institucion,
                        secuencia,
                        tarjeta,
                        cod_comercio,
                        cod_terminal,
                        fecha_transaccion,
                        servicio,
                        monto,
                        moneda,
                        fecha_expiracion,
                        reto,
                        validacionDigital,
                        llave_registro}, this.me_get_Cons_Autho_EcommOperationCompleted, userState);
        }
        
        private void Onme_get_Cons_Autho_EcommOperationCompleted(object arg) {
            if ((this.me_get_Cons_Autho_EcommCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.me_get_Cons_Autho_EcommCompleted(this, new me_get_Cons_Autho_EcommCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Servicio/", ResponseNamespace="http://Servicio/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] me_set_Autho_Ecomm([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string cod_institucion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string secuencia, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string cod_comercio, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string cod_terminal, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string tarjeta, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string nombre_cliente, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string fecha_expiracion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string cvv2, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string monto, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string moneda, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int fecha_envio, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string hora_envio, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string reto, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string validacionDigital, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string llave_registro) {
            object[] results = this.Invoke("me_set_Autho_Ecomm", new object[] {
                        cod_institucion,
                        secuencia,
                        cod_comercio,
                        cod_terminal,
                        tarjeta,
                        nombre_cliente,
                        fecha_expiracion,
                        cvv2,
                        monto,
                        moneda,
                        fecha_envio,
                        hora_envio,
                        reto,
                        validacionDigital,
                        llave_registro});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void me_set_Autho_EcommAsync(string cod_institucion, string secuencia, string cod_comercio, string cod_terminal, string tarjeta, string nombre_cliente, string fecha_expiracion, string cvv2, string monto, string moneda, int fecha_envio, string hora_envio, string reto, string validacionDigital, string llave_registro) {
            this.me_set_Autho_EcommAsync(cod_institucion, secuencia, cod_comercio, cod_terminal, tarjeta, nombre_cliente, fecha_expiracion, cvv2, monto, moneda, fecha_envio, hora_envio, reto, validacionDigital, llave_registro, null);
        }
        
        /// <remarks/>
        public void me_set_Autho_EcommAsync(
                    string cod_institucion, 
                    string secuencia, 
                    string cod_comercio, 
                    string cod_terminal, 
                    string tarjeta, 
                    string nombre_cliente, 
                    string fecha_expiracion, 
                    string cvv2, 
                    string monto, 
                    string moneda, 
                    int fecha_envio, 
                    string hora_envio, 
                    string reto, 
                    string validacionDigital, 
                    string llave_registro, 
                    object userState) {
            if ((this.me_set_Autho_EcommOperationCompleted == null)) {
                this.me_set_Autho_EcommOperationCompleted = new System.Threading.SendOrPostCallback(this.Onme_set_Autho_EcommOperationCompleted);
            }
            this.InvokeAsync("me_set_Autho_Ecomm", new object[] {
                        cod_institucion,
                        secuencia,
                        cod_comercio,
                        cod_terminal,
                        tarjeta,
                        nombre_cliente,
                        fecha_expiracion,
                        cvv2,
                        monto,
                        moneda,
                        fecha_envio,
                        hora_envio,
                        reto,
                        validacionDigital,
                        llave_registro}, this.me_set_Autho_EcommOperationCompleted, userState);
        }
        
        private void Onme_set_Autho_EcommOperationCompleted(object arg) {
            if ((this.me_set_Autho_EcommCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.me_set_Autho_EcommCompleted(this, new me_set_Autho_EcommCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicio/")]
    public partial class me_set_Autho_Ecomm {
        
        private string cod_institucionField;
        
        private string secuenciaField;
        
        private string cod_comercioField;
        
        private string cod_terminalField;
        
        private string tarjetaField;
        
        private string nombre_clienteField;
        
        private string fecha_expiracionField;
        
        private string cvv2Field;
        
        private string montoField;
        
        private string monedaField;
        
        private int fecha_envioField;
        
        private string hora_envioField;
        
        private string retoField;
        
        private string validacionDigitalField;
        
        private string llave_registroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cod_institucion {
            get {
                return this.cod_institucionField;
            }
            set {
                this.cod_institucionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string secuencia {
            get {
                return this.secuenciaField;
            }
            set {
                this.secuenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cod_comercio {
            get {
                return this.cod_comercioField;
            }
            set {
                this.cod_comercioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cod_terminal {
            get {
                return this.cod_terminalField;
            }
            set {
                this.cod_terminalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tarjeta {
            get {
                return this.tarjetaField;
            }
            set {
                this.tarjetaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre_cliente {
            get {
                return this.nombre_clienteField;
            }
            set {
                this.nombre_clienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecha_expiracion {
            get {
                return this.fecha_expiracionField;
            }
            set {
                this.fecha_expiracionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cvv2 {
            get {
                return this.cvv2Field;
            }
            set {
                this.cvv2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int fecha_envio {
            get {
                return this.fecha_envioField;
            }
            set {
                this.fecha_envioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hora_envio {
            get {
                return this.hora_envioField;
            }
            set {
                this.hora_envioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reto {
            get {
                return this.retoField;
            }
            set {
                this.retoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string validacionDigital {
            get {
                return this.validacionDigitalField;
            }
            set {
                this.validacionDigitalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string llave_registro {
            get {
                return this.llave_registroField;
            }
            set {
                this.llave_registroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicio/")]
    public partial class me_get_Cons_Autho_Ecomm {
        
        private string cod_institucionField;
        
        private string secuenciaField;
        
        private string tarjetaField;
        
        private string cod_comercioField;
        
        private string cod_terminalField;
        
        private int fecha_transaccionField;
        
        private string servicioField;
        
        private string montoField;
        
        private string monedaField;
        
        private string fecha_expiracionField;
        
        private string retoField;
        
        private string validacionDigitalField;
        
        private string llave_registroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cod_institucion {
            get {
                return this.cod_institucionField;
            }
            set {
                this.cod_institucionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string secuencia {
            get {
                return this.secuenciaField;
            }
            set {
                this.secuenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tarjeta {
            get {
                return this.tarjetaField;
            }
            set {
                this.tarjetaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cod_comercio {
            get {
                return this.cod_comercioField;
            }
            set {
                this.cod_comercioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cod_terminal {
            get {
                return this.cod_terminalField;
            }
            set {
                this.cod_terminalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int fecha_transaccion {
            get {
                return this.fecha_transaccionField;
            }
            set {
                this.fecha_transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string servicio {
            get {
                return this.servicioField;
            }
            set {
                this.servicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecha_expiracion {
            get {
                return this.fecha_expiracionField;
            }
            set {
                this.fecha_expiracionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reto {
            get {
                return this.retoField;
            }
            set {
                this.retoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string validacionDigital {
            get {
                return this.validacionDigitalField;
            }
            set {
                this.validacionDigitalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string llave_registro {
            get {
                return this.llave_registroField;
            }
            set {
                this.llave_registroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicio/")]
    public partial class me_set_Rever_Ecomm {
        
        private string cod_institucionField;
        
        private string secuenciaField;
        
        private int fecha_transaccionField;
        
        private int fecha_envioField;
        
        private string hora_envioField;
        
        private string retoField;
        
        private string validacionDigitalField;
        
        private string llave_registroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cod_institucion {
            get {
                return this.cod_institucionField;
            }
            set {
                this.cod_institucionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string secuencia {
            get {
                return this.secuenciaField;
            }
            set {
                this.secuenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int fecha_transaccion {
            get {
                return this.fecha_transaccionField;
            }
            set {
                this.fecha_transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int fecha_envio {
            get {
                return this.fecha_envioField;
            }
            set {
                this.fecha_envioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hora_envio {
            get {
                return this.hora_envioField;
            }
            set {
                this.hora_envioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reto {
            get {
                return this.retoField;
            }
            set {
                this.retoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string validacionDigital {
            get {
                return this.validacionDigitalField;
            }
            set {
                this.validacionDigitalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string llave_registro {
            get {
                return this.llave_registroField;
            }
            set {
                this.llave_registroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicio/")]
    public partial class me_get_Con_Autho_RangoFecha_Ecomm {
        
        private string cod_institucionField;
        
        private string cod_comercioField;
        
        private int fecha_inicioField;
        
        private int fecha_finField;
        
        private string retoField;
        
        private string validacionDigitalField;
        
        private string llave_registroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cod_institucion {
            get {
                return this.cod_institucionField;
            }
            set {
                this.cod_institucionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cod_comercio {
            get {
                return this.cod_comercioField;
            }
            set {
                this.cod_comercioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int fecha_inicio {
            get {
                return this.fecha_inicioField;
            }
            set {
                this.fecha_inicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int fecha_fin {
            get {
                return this.fecha_finField;
            }
            set {
                this.fecha_finField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reto {
            get {
                return this.retoField;
            }
            set {
                this.retoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string validacionDigital {
            get {
                return this.validacionDigitalField;
            }
            set {
                this.validacionDigitalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string llave_registro {
            get {
                return this.llave_registroField;
            }
            set {
                this.llave_registroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicio/")]
    public partial class setRegistrarResponse {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicio/")]
    public partial class setRegistrar {
        
        private string cod_institucionField;
        
        private string llave_publicaField;
        
        private string llave_registroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cod_institucion {
            get {
                return this.cod_institucionField;
            }
            set {
                this.cod_institucionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string llave_publica {
            get {
                return this.llave_publicaField;
            }
            set {
                this.llave_publicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string llave_registro {
            get {
                return this.llave_registroField;
            }
            set {
                this.llave_registroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicio/")]
    public partial class getRetoResponse {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicio/")]
    public partial class getReto {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getRetoCompletedEventHandler(object sender, getRetoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRetoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRetoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void setRegistrarCompletedEventHandler(object sender, setRegistrarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setRegistrarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setRegistrarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void me_get_Con_Autho_RangoFecha_EcommCompletedEventHandler(object sender, me_get_Con_Autho_RangoFecha_EcommCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class me_get_Con_Autho_RangoFecha_EcommCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal me_get_Con_Autho_RangoFecha_EcommCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void me_set_Rever_EcommCompletedEventHandler(object sender, me_set_Rever_EcommCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class me_set_Rever_EcommCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal me_set_Rever_EcommCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void me_get_Cons_Autho_EcommCompletedEventHandler(object sender, me_get_Cons_Autho_EcommCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class me_get_Cons_Autho_EcommCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal me_get_Cons_Autho_EcommCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void me_set_Autho_EcommCompletedEventHandler(object sender, me_set_Autho_EcommCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class me_set_Autho_EcommCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal me_set_Autho_EcommCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591