//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWeb.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public decimal PersonaId { get; set; }
        public string PersonaTokenId { get; set; }
        public string PersonaNombres { get; set; }
        public string PersonaApellidos { get; set; }
        public string PersonaCorreo { get; set; }
        public System.DateTime PersonaFechaNacimiento { get; set; }
        public string PersonaTelefono { get; set; }
        public string PersonaUID { get; set; }
        public string PersonaURLFoto { get; set; }
        public string PersonaUsuario { get; set; }
        public System.DateTime PersonaFechaHoraMod { get; set; }
        public decimal TipoPersonaId { get; set; }
        public decimal GeneroId { get; set; }
        public decimal TipoLoginId { get; set; }
        public decimal CiudadId { get; set; }
        public System.DateTime PersonaFechaRegistro { get; set; }
        public decimal EstadoPersonaId { get; set; }
        public decimal PersonaDireccionLast { get; set; }
        public string PersonaDNI { get; set; }
        public decimal TipoDocumentoId { get; set; }
        public string PersonaGeoReal { get; set; }
        public string PersonaClave { get; set; }
        public string PersonaUsuarioMod { get; set; }
        public string PersonaCodigoTelefono { get; set; }
        public decimal PersonaGeoLocalizacionLast { get; set; }
    }
}
