//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWeb.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaDireccion
    {
        public decimal PersonaId { get; set; }
        public decimal PersonaDireccionId { get; set; }
        public decimal TipoDireccionId { get; set; }
        public string PersonaDireccionTitulo { get; set; }
        public string PersonaDireccionGeo { get; set; }
        public string PersonaDireccionDescripcion { get; set; }
        public decimal CiudadDireccionId { get; set; }
        public System.DateTime PersonaDireccionFHMod { get; set; }
        public string PersonaDireccionUsuarioMod { get; set; }
        public decimal EstadoDireccionId { get; set; }
        public string PersonaDireccionDireccion { get; set; }
    }
}
