//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWeb.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequiereServicioProveedores
    {
        public string RequiereServicioId { get; set; }
        public decimal RequiereServicioProveedoresId { get; set; }
        public bool RequiereServicioProveedoresAdj { get; set; }
        public decimal RequiereServicioProvCotizacion { get; set; }
        public System.DateTime RequiereServicioProvFHTrabajo { get; set; }
        public string RequiereServicioProvDescipcion { get; set; }
        public decimal ServicioPersonaId { get; set; }
        public System.DateTime RequiereServicioProvFHResp { get; set; }
        public Nullable<decimal> StatusRequiereId { get; set; }
    }
}
